dist: xenial,
language: node_js
node_js:
  - 12

stages:
  - test
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: npm run test
    - stage: deploy
      name: "Deploy"
      script:
      - npm run build
      - npm run semantic-release
