sudo: false
language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

stages:
  - install
  - test
  - name: deploy
    if: branch = master AND (NOT (type IN (push, pull_request)))

jobs:
  include:
    - stage: install
      name: "Install"
      script: npm install
    - stage: test
      name: "Unit Tests"
      script: npm run test
    - stage: deploy
      name: "Deploy"
      script:
      - npm run build
      - npm run semantic-release
