sudo: false
language: node_js
node_js:
  - 12

cache:
  npm: false
  directories:
    - node_modules

stages:
  - install
  - test
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    - stage: install
      name: "Install"
      script: npm install
    - stage: test
      name: "Unit Tests"
      script: npm run test
    - stage: deploy
      name: "Deploy"
      script:
      - npm run build
      - npm run semantic-release
