sudo: false
language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

stages:
  - install
  - test
  - name: deploy
    if: branch == master AND (NOT (type IN (push, pull_request)))

jobs:
  include:
    - stage: install
      script: npm install
      skip_cleanup: true
    - stage: test
      script: npm run test
      skip_cleanup: true
    - stage: deploy
      script:
      - npm run build
      - npm run semantic-release
