name: Release npm package

on:
  push:
    branches:
      - master
permissions:
  id-token: write # Required for OIDC
  contents: write     

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: NODE_AUTH_TOKEN="" npm run semantic-release --access public --provenance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
